// 'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";

import QueryProvider from "@components/QueryProvider";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digidine",
  description: "Generated by create next app",
};

export default function ClientPageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-backgroundColor `}
      >
        <QueryProvider>
          <MantineProvider>{children}</MantineProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
