import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";

import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { ModalsProvider } from "@mantine/modals";
import { Notifications } from "@mantine/notifications";
import "@mantine/notifications/styles.css";
import "@mantine/nprogress/styles.css";

import QueryProvider from "../../components/QueryProvider";
import RouterTransition from "../../components/RouterTransition";
import { getDictionary } from "../messages";
import "./../../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digidine",
  description: "Generated by create next app",
};

export default async function DashBoardLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: "en" | "hd" | "sp" }>;
}>) {
  const theme = (await cookies()).get("theme");

  return (
    <html lang={(await params).locale} className={`${theme?.value}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-backgroundColor `}
      >
        <QueryProvider>
          <MantineProvider defaultColorScheme="auto">
            <ModalsProvider>
              <RouterTransition />
              <Notifications position="top-right" />
              {children}
            </ModalsProvider>
          </MantineProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
