import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import "@mantine/notifications/styles.css";
import { Notifications } from "@mantine/notifications";
import "./../globals.css";
import QueryProvider from "../components/QueryProvider";
import RouterTransition from "../components/RouterTransition";
import { ThemeProvider } from "../context/ThemeProvider";
import '@mantine/nprogress/styles.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-backgroundColor `}
      >
        <QueryProvider>
          <MantineProvider defaultColorScheme="auto">
            <RouterTransition />
            <Notifications position="top-right" />
            <ThemeProvider>
              {children}
            </ThemeProvider>
          </MantineProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
