// 'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import "./../globals.css";
import QueryProvider from "../components/QueryProvider";

import { NavigationProgress } from "@mantine/nprogress";
import RouterTransition from "../components/RouterTransition";
import { cookies } from "next/headers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digidine",
  description: "Generated by create next app",
};

export default async function ClientPageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const theme = (await cookies()).get("theme");
  return (
    <html lang="en" className={`${theme?.value}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-backgroundColor `}
      >
        <QueryProvider>
          <MantineProvider>{children}</MantineProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
